sudo: required

services:
  - docker

before_install:
  # Use whackpad image from master as Docker is basically a stub for now.
  # - docker pull whackpad/whackpad
  - docker build -t whackpad .

script:
  - docker run -d -p 127.0.0.1:9000:9000 -v $TRAVIS_BUILD_DIR:/etc/hackpad/src whackpad whackpad
  - sleep 15
  - curl -k -b ~/cookies.txt http://127.0.0.1:9000/ep/unit-tests/run
